# Generated by Django 3.2.13 on 2026-06-20 03:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMetaData',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metadata', serialize=False, to='auth.user')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('pending', 'Pending'), ('archived', 'Archived'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('studio', models.BooleanField(default=False)),
                ('careers_app', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User Metadata',
                'verbose_name_plural': 'User Metadata',
            },
        ),
    ]
