# Generated by Django 3.2.13 on 2026-06-20 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0012_alter_college_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityProgrammes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('short_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(choices=[('1_year', '1 Year'), ('2_year', '2 Year'), ('3_year', '3 Year'), ('4_year', '4 Year'), ('5_year', '5 Year')], default='1_year', max_length=20)),
                ('enable_careers_app', models.BooleanField(default=False)),
                ('enable_mystudio', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.college')),
            ],
            options={
                'verbose_name': 'University Programme',
                'verbose_name_plural': 'University Programmes',
            },
        ),
        migrations.CreateModel(
            name='UniversityProgrammesYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('number_of_year', models.CharField(max_length=50)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_years', to='university_programme.universityprogrammes')),
            ],
            options={
                'verbose_name': 'University Programme Year',
                'verbose_name_plural': 'University Programme Years',
            },
        ),
        migrations.CreateModel(
            name='UniversityProgrammesYearSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('programme_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_sections', to='university_programme.universityprogrammesyear')),
            ],
            options={
                'verbose_name': 'University Programme Year Section',
                'verbose_name_plural': 'University Programme Year Sections',
            },
        ),
        migrations.CreateModel(
            name='UniversityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('group_type', models.CharField(choices=[('career_track', 'Career Track'), ('teaching_group', 'Teaching Group')], max_length=50)),
                ('admin', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('colour', models.CharField(blank=True, max_length=50, null=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_programme.universityprogrammes')),
                ('students', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.college')),
            ],
            options={
                'verbose_name': 'University Group',
                'verbose_name_plural': 'University Groups',
            },
        ),
        migrations.CreateModel(
            name='UniversityBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.college')),
            ],
            options={
                'verbose_name': 'University Batch',
                'verbose_name_plural': 'University Batches',
            },
        ),
        migrations.CreateModel(
            name='UniversityProgrammesEnrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_programme.universityprogrammes')),
                ('programme_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_programme.universityprogrammesyearsection')),
                ('programme_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_programme.universityprogrammesyear')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_enrolments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'University Programme Enrolment',
                'verbose_name_plural': 'University Programme Enrolments',
                'unique_together': {('programme', 'user')},
            },
        ),
    ]
