# Generated by Django 3.2.13 on 2023-01-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_modes', '0013_auto_20200115_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemode',
            name='currency',
            field=models.CharField(default='inr', max_length=8),
        ),
        migrations.AlterField(
            model_name='coursemodesarchive',
            name='currency',
            field=models.CharField(default='inr', max_length=8),
        ),
        migrations.AlterField(
            model_name='historicalcoursemode',
            name='currency',
            field=models.CharField(default='inr', max_length=8),
        ),
    ]
