# Generated by Django 3.2.13 on 2023-07-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_modes', '0014_auto_20230104_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemode',
            name='tax_info',
            field=models.CharField(default='Price not inclusive of GST', max_length=512, verbose_name='Tax Information'),
        ),
        migrations.AddField(
            model_name='historicalcoursemode',
            name='tax_info',
            field=models.CharField(default='Price not inclusive of GST', max_length=512, verbose_name='Tax Information'),
        ),
        migrations.AlterField(
            model_name='coursemode',
            name='_expiration_datetime',
            field=models.DateTimeField(blank=True, db_column='expiration_datetime', default=None, help_text='OPTIONAL: After this date/time, users will no longer be able to enroll in this mode. Leave this blank if users can enroll in this mode until enrollment closes for the course. NOTE: Upgrade Deadline date must be later than the course enrollment end date in studio.', null=True, verbose_name='Upgrade Deadline'),
        ),
        migrations.AlterField(
            model_name='historicalcoursemode',
            name='_expiration_datetime',
            field=models.DateTimeField(blank=True, db_column='expiration_datetime', default=None, help_text='OPTIONAL: After this date/time, users will no longer be able to enroll in this mode. Leave this blank if users can enroll in this mode until enrollment closes for the course. NOTE: Upgrade Deadline date must be later than the course enrollment end date in studio.', null=True, verbose_name='Upgrade Deadline'),
        ),
    ]
