# Generated by Django 3.2.13 on 2023-07-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_modes', '0015_auto_20230705_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemode',
            name='tax_info',
            field=models.CharField(blank=True, default='Price not inclusive of GST', max_length=512, null=True, verbose_name='Tax Information'),
        ),
        migrations.AlterField(
            model_name='historicalcoursemode',
            name='tax_info',
            field=models.CharField(blank=True, default='Price not inclusive of GST', max_length=512, null=True, verbose_name='Tax Information'),
        ),
    ]
