# Generated by Django 3.2.13 on 2023-06-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0034_auto_20220401_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcertificate',
            name='download_url',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='historicalgeneratedcertificate',
            name='download_url',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
