# Generated by Django 3.2.13 on 2022-10-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_userprofile_is_archive'),
        ('student', '0044_courseenrollmentcelebration_celebrate_weekly_goal'),
    ]

    operations = [
    ]
