# Generated by Django 3.2.13 on 2022-10-20 12:51

import common.djangoapps.course_modes.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0045_merge_20221020_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('country_id', models.IntegerField(blank=True, null=True, verbose_name='Country Id')),
                ('country_name', models.CharField(max_length=50, verbose_name='Country Name')),
                ('countries_iso_code_2', models.CharField(max_length=50, verbose_name='ISO2')),
                ('countries_iso_code_3', models.CharField(max_length=50, verbose_name='ISO3')),
                ('address_format_id', models.IntegerField(blank=True, null=True, verbose_name='Address ID')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Country',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='is_purchased',
            field=models.BooleanField(default=False, verbose_name='Single Course Purchase'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='purchase_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='purchase_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseenrollment',
            name='is_purchased',
            field=models.BooleanField(default=False, verbose_name='Single Course Purchase'),
        ),
        migrations.AddField(
            model_name='historicalcourseenrollment',
            name='purchase_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseenrollment',
            name='purchase_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='college_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mail_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be entered in the format: "9999999999". Up to 10 digits allowed.', regex='^\\+?1?\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='mode',
            field=models.CharField(default=common.djangoapps.course_modes.models.CourseMode.get_default_mode_slug, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcourseenrollment',
            name='mode',
            field=models.CharField(default=common.djangoapps.course_modes.models.CourseMode.get_default_mode_slug, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='Archived User'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_college_admin',
            field=models.BooleanField(default=False, verbose_name='organization Admin'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_college_subadmin',
            field=models.BooleanField(default=False, verbose_name='Group Admin'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('zone_id', models.IntegerField(blank=True, null=True, verbose_name='Zone Id')),
                ('zone_country_id', models.IntegerField(blank=True, null=True, verbose_name='Zone_Country Id')),
                ('zone_code', models.CharField(max_length=50, verbose_name='Zone Code')),
                ('zone_name', models.CharField(max_length=50, verbose_name='Zone Name')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'State',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='new_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_country', to='student.country'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.state'),
        ),
    ]
