# Generated by Django 3.2.13 on 2023-02-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0046_auto_20221020_1251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalCourseEnrollment',
        ),
    ]
