# Generated by Django 3.2.13 on 2024-01-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0048_historicalcourseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollmentallowed',
            name='enrollment_mode',
            field=models.CharField(default='audit', max_length=64),
        ),
    ]
